[workspace]
members = ["crates/*", "crates/app/src-tauri"]
default-members = ["crates/cli"]
resolver = "3"

[workspace.package]
authors = ["Dylan Manuel"]
description = "A framework for creating and curating high-quality code datasets tailored for large language models"
categories = ["artificial-intelligence", "security"]
keywords = [
    "large-language-models",
    "automation",
    "reverse-engineering",
    "software-security",
    "dataset-generation",
]
homepage = "https://codablellm.readthedocs.io/"
license = "MIT"
version = "2.0.0-alpha.1"
edition = "2024"
rust-version = "1.96"


[workspace.dependencies]
codablellm-core = { path = "crates/core", version = "2.0.0" }

strum = { version = "0.28", features = ["derive"] }
thiserror = "2"
futures-util = "0.3"
color-eyre = "0.6"
human-panic = "2"
mimalloc = "0.1"
serde = { version = "1", features = ["derive"] }
toml = "1"
tracing = "0.1"
# TODO: figure out the bare-minimum needed for tokio
tokio = { version = "1", features = ["full"] }
