version: "0.2"
ignorePaths:
  - target/**
  - "**/*.lock"
  - .venv/**
  - dist/**
dictionaryDefinitions: []
dictionaries:
  - python
  - rust
words:
  - cdylib
  - cksum
  - codablellm
  - flate
  - indicatif
  - maturin
  - pyfunction
  - pymodule
  - reqwest
  - sexp
  - thiserror
ignoreWords: []
import: []
