version: "0.2"
ignorePaths:
  - target/**
  - "**/*.lock"
  - .venv/**
  - dist/**
dictionaryDefinitions: []
dictionaries:
  - python
  - rust
words:
  - cdylib
  - cksum
  - cnqoj
  - codablellm
  - flate
  - Forgejo
  - Gitea
  - goreleaser
  - indicatif
  - leptos
  - maturin
  - mimalloc
  - mlua
  - modeline
  - modelines
  - pyfunction
  - pymodule
  - reqwest
  - rhai
  - sexp
  - starlark
  - tauri
  - thiserror
ignoreWords: []
import: []
