[project]
name = "codablellm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = []

[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
module-name = "codablellm._core"
manifest-path = "crates/py/Cargo.toml"
python-source = "python"
features = ["pyo3/extension-module"]

[tool.uv.workspace]
members = [
    "foo",
]
