[package]
name = "codablellm-cli"
version = "0.1.0"
edition.workspace = true
description.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true

[[bin]]
name = "codablellm"
path = "src/main.rs"

[dependencies]
codablellm = { workspace = true, features = ["full", "value-enums"] }

color-eyre.workspace = true
human-panic.workspace = true
strum.workspace = true
mimalloc.workspace = true
log.workspace = true

clap = { version = "4", features = ["derive"] }
env_logger = "0.11"
