[package]
name = "codablellm-pyo3"
description.workspace = true
authors.workspace = true
categories.workspace = true
keywords.workspace = true
homepage.workspace = true
license.workspace = true
rust-version.workspace = true
version.workspace = true
edition.workspace = true

[lib]
name = "_core"
crate-type = ["cdylib"]

[dependencies]
codablellm-core = { path = "../core", default-features = false }

pyo3 = { version = "0.29", features = ["extension-module"] }
